<a href="https://colab.research.google.com/github/FeraMaks/test/blob/main/10_dataset_and_dataloader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##✈Import libraries

In [1]:
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

from google.colab import drive

In [2]:
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


#Data set

In [7]:
class WineDataset(Dataset):

  def __init__(self, transform=None):
    #data loading
    xy = np.loadtxt('/content/drive/MyDrive/Dataset/wine.csv', delimiter=',', dtype=np.float32, skiprows=1)
    self.x = (xy[:, 1:])
    self.y = (xy[:,[0]]) #n
    self.n_samples = xy.shape[0]
    self.transform = transform

  def __getitem__(self, index):
    sample = self.x[index], self.y[index]

    if self.transform:
      sample = self.transform(sample)

    return sample

  def __len__(self):
    return self.n_samples

In [4]:
class ToTensor:
  def __call__(self,sample):
    inputs, targets = sample
    return torch.from_numpy(inputs), torch.from_numpy(targets)

In [18]:
class MultTransform:
  def __init__(self, factor):
    self.factor = factor

  def __call__(self,sample):
    inputs, targets = sample
    inputs *= self.factor
    return inputs, targets

In [16]:
dataset = WineDataset(transform=ToTensor())
first_data = dataset[0]
print(first_data)

(tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]), tensor([1.]))


In [19]:
composed = torchvision.transforms.Compose([ToTensor(), MultTransform(0.5)])
dataset = WineDataset(transform=composed)
first_data = dataset[0]
print(first_data)

(tensor([7.1150e+00, 8.5500e-01, 1.2150e+00, 7.8000e+00, 6.3500e+01, 1.4000e+00,
        1.5300e+00, 1.4000e-01, 1.1450e+00, 2.8200e+00, 5.2000e-01, 1.9600e+00,
        5.3250e+02]), tensor([1.]))


In [9]:
dataloader = DataLoader(dataset=dataset, batch_size = 4, shuffle=True, num_workers=2)

In [11]:
dataiter = iter(dataloader)
data = dataiter.next()
features, labels = data
print(features, labels)
#inputs=features, targets=labels

tensor([[1.2080e+01, 2.0800e+00, 1.7000e+00, 1.7500e+01, 9.7000e+01, 2.2300e+00,
         2.1700e+00, 2.6000e-01, 1.4000e+00, 3.3000e+00, 1.2700e+00, 2.9600e+00,
         7.1000e+02],
        [1.2700e+01, 3.5500e+00, 2.3600e+00, 2.1500e+01, 1.0600e+02, 1.7000e+00,
         1.2000e+00, 1.7000e-01, 8.4000e-01, 5.0000e+00, 7.8000e-01, 1.2900e+00,
         6.0000e+02],
        [1.2420e+01, 1.6100e+00, 2.1900e+00, 2.2500e+01, 1.0800e+02, 2.0000e+00,
         2.0900e+00, 3.4000e-01, 1.6100e+00, 2.0600e+00, 1.0600e+00, 2.9600e+00,
         3.4500e+02],
        [1.2690e+01, 1.5300e+00, 2.2600e+00, 2.0700e+01, 8.0000e+01, 1.3800e+00,
         1.4600e+00, 5.8000e-01, 1.6200e+00, 3.0500e+00, 9.6000e-01, 2.0600e+00,
         4.9500e+02]]) tensor([[2.],
        [3.],
        [2.],
        [2.]])


# Training loop (empty_

In [10]:
num_epoch = 2
batch_size = 4
total_samples = len(dataset)
n_iteration = math.ceil(total_samples/batch_size)

In [12]:
for epoch in range(num_epoch):
  for i, (inputs, targets) in enumerate (dataloader):
    #forward
    #backward
    #update
    if (i+1)% 5 == 0:
      print(f'epoch {epoch}/{num_epoch}, iteration {i+1}/{n_iteration},inputs {inputs.shape}, targets {targets.shape}')

epoch 0/2, iteration 5/45,inputs torch.Size([4, 13]), targets torch.Size([4, 1])
epoch 0/2, iteration 10/45,inputs torch.Size([4, 13]), targets torch.Size([4, 1])
epoch 0/2, iteration 15/45,inputs torch.Size([4, 13]), targets torch.Size([4, 1])
epoch 0/2, iteration 20/45,inputs torch.Size([4, 13]), targets torch.Size([4, 1])
epoch 0/2, iteration 25/45,inputs torch.Size([4, 13]), targets torch.Size([4, 1])
epoch 0/2, iteration 30/45,inputs torch.Size([4, 13]), targets torch.Size([4, 1])
epoch 0/2, iteration 35/45,inputs torch.Size([4, 13]), targets torch.Size([4, 1])
epoch 0/2, iteration 40/45,inputs torch.Size([4, 13]), targets torch.Size([4, 1])
epoch 0/2, iteration 45/45,inputs torch.Size([2, 13]), targets torch.Size([2, 1])
epoch 1/2, iteration 5/45,inputs torch.Size([4, 13]), targets torch.Size([4, 1])
epoch 1/2, iteration 10/45,inputs torch.Size([4, 13]), targets torch.Size([4, 1])
epoch 1/2, iteration 15/45,inputs torch.Size([4, 13]), targets torch.Size([4, 1])
epoch 1/2, iterati