<a href="https://colab.research.google.com/github/FeraMaks/test/blob/main/17_nLazy_Save%26Load_Method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [2]:
class Model(nn.Module):
  def __init__(self, n_input_features):
    super(Model, self).__init__()
    self.linear = nn.Linear(n_input_features, 1)
  
  def forward(self, x):
    y_pred = torch.sigmoid(self.linear(x))
    return y_pred

model = Model(n_input_features=6)
#train your model...

for param in model.parameters():
  print(param)
FILE = "model.pth"
torch.save(model.state_dict(), FILE)
#model = torch.load(FILE)
#model.eval()

loaded_model = Model(n_input_features=6)
loaded_model.load_state_dict(torch.load(FILE))
loaded_model.eval()

for param in loaded_model.parameters():
  print(param)

Parameter containing:
tensor([[ 0.2422,  0.2903, -0.2093,  0.0659,  0.2346, -0.2866]],
       requires_grad=True)
Parameter containing:
tensor([-0.2905], requires_grad=True)
Parameter containing:
tensor([[ 0.2422,  0.2903, -0.2093,  0.0659,  0.2346, -0.2866]],
       requires_grad=True)
Parameter containing:
tensor([-0.2905], requires_grad=True)
