<a href="https://colab.research.google.com/github/FeraMaks/test/blob/main/lab2_25_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import numpy.linalg as lina
import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import Axes3D
import pandas as pd

In [2]:
N1 = 100
N2 = 100
L1 = 1
L2 = 1
X1 = np.linspace(0,L1,N1)
X2 = np.linspace(0,L2,N2)
Tbot = np.zeros((1,N1))
Ttop = np.zeros((N2,1))
Ta, Tb, Tc = 200, 300, 400
a = 1/((X1[1]-X1[0])**2)
b = 1/((X2[1]-X2[0])**2)
c = -2*(a+b)

In [3]:
K = np.zeros(((N1-1)*(N2-1),(N1-1)*(N2-1)))
T = np.zeros(((N1),(N2)))
P = np.zeros(((N1-1)*(N2-1),1))
T

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [4]:
for j in range (N2-1):
  for i in range (N1-1):
    K[i+j*(N1-1),i+j*(N2-1)] = c
    if i != N2-2:
      K[i+1+j*(N1-1),i+j*(N2-1)] = a
    if j != N2-2:
      K[i-1+j*(N1-1),i+j*(N2-1)] = a
      K[i+j*(N1-1),i+(j+1)*(N2-1)] = b
    if i == (N1-2):
      K[i+j*(N1-1),i+j*(N2-1)] = c+a
  if j == (N2-2):
    for i in range (N1-1):
      K[i+j*(N1-1),i+j*(N2-1)] = c+b
    if i == (N1-2):
      K[i+j*(N1-1),i+j*(N2-1)] = c+b+a
K

array([[-39204.,   9801.,      0., ...,      0.,      0.,      0.],
       [  9801., -39204.,   9801., ...,      0.,      0.,      0.],
       [     0.,   9801., -39204., ...,      0.,      0.,      0.],
       ...,
       [     0.,      0.,      0., ..., -29403.,      0.,      0.],
       [     0.,      0.,      0., ...,   9801., -29403.,      0.],
       [  9801.,      0.,      0., ...,      0.,   9801., -19602.]])

In [5]:
for i in range (N1):
  Tbot[0,i] = (Tc-Ta)/L2*X2[i]+Ta
Tbot

array([[200.        , 202.02020202, 204.04040404, 206.06060606,
        208.08080808, 210.1010101 , 212.12121212, 214.14141414,
        216.16161616, 218.18181818, 220.2020202 , 222.22222222,
        224.24242424, 226.26262626, 228.28282828, 230.3030303 ,
        232.32323232, 234.34343434, 236.36363636, 238.38383838,
        240.4040404 , 242.42424242, 244.44444444, 246.46464646,
        248.48484848, 250.50505051, 252.52525253, 254.54545455,
        256.56565657, 258.58585859, 260.60606061, 262.62626263,
        264.64646465, 266.66666667, 268.68686869, 270.70707071,
        272.72727273, 274.74747475, 276.76767677, 278.78787879,
        280.80808081, 282.82828283, 284.84848485, 286.86868687,
        288.88888889, 290.90909091, 292.92929293, 294.94949495,
        296.96969697, 298.98989899, 301.01010101, 303.03030303,
        305.05050505, 307.07070707, 309.09090909, 311.11111111,
        313.13131313, 315.15151515, 317.17171717, 319.19191919,
        321.21212121, 323.23232323, 325.

In [6]:
for i in range (N2):
  Ttop[i,0] = (Tb-Ta)/L1*X1[i]+Ta
Ttop

array([[200.        ],
       [201.01010101],
       [202.02020202],
       [203.03030303],
       [204.04040404],
       [205.05050505],
       [206.06060606],
       [207.07070707],
       [208.08080808],
       [209.09090909],
       [210.1010101 ],
       [211.11111111],
       [212.12121212],
       [213.13131313],
       [214.14141414],
       [215.15151515],
       [216.16161616],
       [217.17171717],
       [218.18181818],
       [219.19191919],
       [220.2020202 ],
       [221.21212121],
       [222.22222222],
       [223.23232323],
       [224.24242424],
       [225.25252525],
       [226.26262626],
       [227.27272727],
       [228.28282828],
       [229.29292929],
       [230.3030303 ],
       [231.31313131],
       [232.32323232],
       [233.33333333],
       [234.34343434],
       [235.35353535],
       [236.36363636],
       [237.37373737],
       [238.38383838],
       [239.39393939],
       [240.4040404 ],
       [241.41414141],
       [242.42424242],
       [243

In [7]:
for j in range (N2-1):
  for i in range (N1-1):
    if i == 0:
      P[i+j*(N1-1),0] = -a*Ttop[j]
    if j == 0:
      P[i+j*(N1-1),0] = -a*Ttop[i,0]-b*Tbot[0,i]
      P[i+1+j*(N1-1),0] = -b*Tbot[0,i]
P

array([[-3920400.],
       [-3950100.],
       [-3979800.],
       ...,
       [       0.],
       [       0.],
       [       0.]])

In [ ]:
T = lina.solve(K, P)
T

In [ ]:
T = np.reshape(T,(N1-1,N2-1))
T


In [ ]:
Ttop = Ttop[::-1]
Ttop = Ttop[0:N2-1]
Ttop.shape

In [ ]:
T = np.concatenate((Ttop, T), axis=1)
T

In [ ]:
T = np.concatenate((T, Tbot), axis=0)
T

In [ ]:
np.reshape(T[0,:N1],(1,T[0,:N1].shape[0]))
T = np.concatenate((np.reshape(T[0,:N1],(1,T[0,:N1].shape[0])), T), axis=0)
np.reshape(T[:,T.shape[1]-1],(N2+1,1))
T = np.concatenate((T, np.reshape(T[:,T.shape[1]-1],(N2+1,1))), axis=1)
T

In [ ]:
X1 = np.linspace(0,L1,N1+1)
X2 = np.linspace(0,L2,N2+1)

In [ ]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(X1, X2, T, cmap=cm.jet, linewidth=1, vmin = 0, vmax = 1000)
ax.set_xlabel('X1')
ax.set_ylabel('Y2')
ax.set_zlabel('Temp')
fig.tight_layout()

In [ ]:
pd.DataFrame(data=T)