<a href="https://colab.research.google.com/github/FeraMaks/test/blob/main/lab2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
import numpy.linalg as lina
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [2]:
N1 = 5
N2 = 5
L1 = 1
L2 = 1
X1 = np.linspace(0,L1,N1)
X2 = np.linspace(0,L2,N2)
Tbot = np.zeros((1,N1))
Ttop = np.zeros((N2,1))
Ta, Tb, Tc = 200, 300, 400
a = 1/((X1[1]-X1[0])**2)
b = 1/((X2[1]-X2[0])**2)
c = -2*(a+b)
X1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [3]:
K = np.zeros(((N1-1)*(N2-1),(N1-1)*(N2-1)))
T = np.zeros(((N1),(N2)))
P = np.zeros(((N1-1)*(N2-1),1))
T

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
for j in range (N2-1):
  for i in range (N1-1):
    K[i+j*(N1-1),i+j*(N2-1)] = c
    if i != N2-2:
      K[i+1+j*(N1-1),i+j*(N2-1)] = a
    if j != N2-2:
      K[i-1+j*(N1-1),i+j*(N2-1)] = a
      K[i+j*(N1-1),i+(j+1)*(N2-1)] = b
    if i == (N1-2):
      K[i+j*(N1-1),i+j*(N2-1)] = c+a
  if j == (N2-2):
    for i in range (N1-1):
      K[i+j*(N1-1),i+j*(N2-1)] = c+b
    if i == (N1-2):
      K[i+j*(N1-1),i+j*(N2-1)] = c+b+a
K

array([[-64.,  16.,   0.,   0.,  16.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.],
       [ 16., -64.,  16.,   0.,   0.,  16.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.],
       [  0.,  16., -64.,  16.,   0.,   0.,  16.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,  16., -48.,  16.,   0.,   0.,  16.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0., -64.,  16.,   0.,   0.,  16.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,  16., -64.,  16.,   0.,   0.,  16.,   0.,
          0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,  16., -64.,  16.,   0.,   0.,  16.,
          0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,  16., -48.,  16.,   0.,   0.,
         16.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., -64.,  16.,   0.,
          0.,  16.,   

In [5]:
for i in range (N1):
  Tbot[0,i] = (Tc-Ta)/L2*X2[i]+Ta
Tbot

array([[200., 250., 300., 350., 400.]])

In [6]:
for i in range (N2):
  Ttop[i,0] = (Tb-Ta)/L1*X1[i]+Ta
Ttop

array([[200.],
       [225.],
       [250.],
       [275.],
       [300.]])

In [7]:
(b-a)/L1

0.0

In [10]:
for j in range (N2-1):
  for i in range (N1-1):
    if i == 0:
      P[i+j*(N1-1),0] = -a*Ttop[j]
    if j == 0:
      P[i+j*(N1-1),0] = -a*Ttop[i,0]-b*Tbot[0,i]
      P[i+1+j*(N1-1),0] = -b*Tbot[0,i]
P

array([[ -6400.],
       [ -7600.],
       [ -8800.],
       [-10000.],
       [ -3600.],
       [     0.],
       [     0.],
       [     0.],
       [ -4000.],
       [     0.],
       [     0.],
       [     0.],
       [ -4400.],
       [     0.],
       [     0.],
       [     0.]])

In [11]:
T = lina.solve(K, P)
T

array([[184.50230837],
       [248.42745093],
       [295.47084725],
       [354.78638943],
       [ 89.58178253],
       [ 38.73664813],
       [ 28.66954862],
       [ 54.3065385 ],
       [ 94.59048201],
       [ 36.69526135],
       [ 21.63500785],
       [ 39.65958488],
       [ 91.66666667],
       [ 30.55555556],
       [ 10.18518519],
       [ 97.34374678]])

In [12]:
T = np.reshape(T,(4,4))
T

array([[184.50230837, 248.42745093, 295.47084725, 354.78638943],
       [ 89.58178253,  38.73664813,  28.66954862,  54.3065385 ],
       [ 94.59048201,  36.69526135,  21.63500785,  39.65958488],
       [ 91.66666667,  30.55555556,  10.18518519,  97.34374678]])