<a href="https://colab.research.google.com/github/FeraMaks/test/blob/main/lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import numpy.linalg as lina


In [2]:
a = 200
b = 300
c = 400
N1 = 5
N2 = 5

In [3]:
K = np.zeros(((N1-1)*(N2-1),(N1-1)*(N2-1)))
T = np.zeros(((N1-1)*(N2-1),1))
P = np.zeros(((N1-1)*(N2-1),1))
K

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [4]:
for j in range (N2-1):
  for i in range (N1-1):
    K[i+j*(N1-1),i+j*(N2-1)] = c
    if i != N2-2:
      K[i+1+j*(N1-1),i+j*(N2-1)] = a
    if j != N2-2:
      K[i-1+j*(N1-1),i+j*(N2-1)] = a
      K[i+j*(N1-1),i+(j+1)*(N2-1)] = b
    if i == (N1-2):
      K[i+j*(N1-1),i+j*(N2-1)] = c+a
  if j == (N2-2):
    for i in range (N1-1):
      K[i+j*(N1-1),i+j*(N2-1)] = c+b
    if i == (N1-2):
      K[i+j*(N1-1),i+j*(N2-1)] = c+b+a
K

array([[400., 200.,   0.,   0., 300.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.],
       [200., 400., 200.,   0.,   0., 300.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.],
       [  0., 200., 400., 200.,   0.,   0., 300.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.],
       [  0.,   0., 200., 600., 200.,   0.,   0., 300.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0., 400., 200.,   0.,   0., 300.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0., 200., 400., 200.,   0.,   0., 300.,   0.,
          0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0., 200., 400., 200.,   0.,   0., 300.,
          0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0., 200., 600., 200.,   0.,   0.,
        300.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 400., 200.,   0.,
          0., 300.,   

In [5]:
for j in range (N2-1):
  for i in range (N1-1):
    if i == 0:
      P[i+j*(N1-1),0] = -a
  if j == 0:
    for i in range (N1-1):
      if i == 0:
        P[i+j*(N1-1),0] = -a-b
        P[i+1+j*(N1-1),0] = -b
  if j == (N2-2):
    for i in range (N1-1):
      if i == 0:
        P[i+j*(N1-1),0] = -a
P

array([[-500.],
       [-300.],
       [   0.],
       [   0.],
       [-200.],
       [   0.],
       [   0.],
       [   0.],
       [-200.],
       [   0.],
       [   0.],
       [   0.],
       [-200.],
       [   0.],
       [   0.],
       [   0.]])