<a href="https://colab.research.google.com/github/FeraMaks/test/blob/main/Softmax_CrossEntropy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Import libraries

In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
def softmax(x):
  return np.exp(x)/np.sum(np.exp(x),axis=0)

x = np.array([2.0, 1.0, 0.1])
outputs = softmax(x)
print('softmax numpy:', outputs)

x = torch.tensor([2.0, 1.0, 0.1])
outputs = torch.softmax(x, dim=0)
print(outputs)

softmax numpy: [0.65900114 0.24243297 0.09856589]
tensor([0.6590, 0.2424, 0.0986])


Cross_entropy

In [3]:
def cross_entropy(actual, predicted):
  loss = -np.sum(actual = np.log(predicted))
  return loss # / float(predicted.shape[0])

#y must be one hot encoded
#if class 0: [1 0 0]
#if class 1: [0 1 0]
#if class 2: [0 0 1]
Y = np.array([1, 0, 0])

#y_pred has probabilities
Y_pred_good = np.array([0.7, 0.2, 0.1])
Y_pred_bad = np.array([0.1, 0.3, 0.6])
l1 = cross_entropy(Y, Y_pred_good)
l2 = cross_entropy(Y, Y_pred_bad)
print(f'Loss1 numpy: {l1:.4f}')
print(f'Loss2 numpy: {l2:.4f}')

TypeError: ignored

In [7]:
loss = nn.CrossEntropyLoss()

#3 samples
Y = torch.tensor([2, 0, 1])
# nsamples x nclasses = 3x3
Y_pred_good = torch.tensor([[0.1, 1.0, 2.1],[2.0, 1.0, 0.1],[0.1, 3.0, 0.1]])
Y_pred_bad = torch.tensor([[2.1, 1.0, 0.1],[0.1, 1.0, 2.1],[0.1, 3.0, 0.1]])

l1 = loss(Y_pred_good, Y)
l2 = loss(Y_pred_bad, Y)

print(l1.item())
print(l2.item())

_, predictions1 = torch.max(Y_pred_good, 1)
_, predictions2 = torch.max(Y_pred_bad, 1)
print(predictions1)
print(predictions2)

0.3018244206905365
1.6241613626480103
tensor([2, 0, 1])
tensor([0, 2, 1])


Multi class

In [9]:
#Multiclass problem
class NeuralNet2(nn.Module):
  def __init__(self, input_size, hidden_size, num_classes):
      super(NeuralNet2, self).__init__()
      self.linear1 = nn.Linear(input_size, hidden_size)
      self.relu = nn.ReLU()
      self.linear2 = nn.Linear(hidden_size, num_classes)
  
  def forward(self, x):
    out = self.linear1(x)
    out = self.relu(out)
    out = self.linear2(out)
    #no softmax at the end
    return out

model = NeuralNet2(input_size=28*28, hidden_size=5, num_classes=3)
criterion = nn.CrossEntropyLoss() # applies softmax

Binary class

In [11]:
#Multiclass problem
class NeuralNet2(nn.Module):
  def __init__(self, input_size, hidden_size):
      super(NeuralNet2, self).__init__()
      self.linear1 = nn.Linear(input_size, hidden_size)
      self.relu = nn.ReLU()
      self.linear2 = nn.Linear(hidden_size, 1)
  
  def forward(self, x):
    out = self.linear1(x)
    out = self.relu(out)
    out = self.linear2(out)
    #sigmoid at the end
    y_pred = torch.sigmoid(out)
    return out

model = NeuralNet2(input_size=28*28, hidden_size=5)
criterion = nn.BCELoss()